//! Python target — entities → dataclasses, operations → Protocol, api → route table.

use std::path::PathBuf;

use anyhow::Result;
use idl_graph::GraphDoc;

use super::{
    node_name, pascal_case, safe_ident, snake_case, EmitReport, EmittedFile, GraphEmitter,
};

pub struct PythonEmitter;

impl GraphEmitter for PythonEmitter {
    fn target(&self) -> &str {
        "python"
    }

    fn emit(&self, graph: &GraphDoc) -> Result<EmitReport> {
        let mut report = EmitReport {
            target: "python".into(),
            files: Vec::new(),
            nodes_emitted: 0,
        };

        let mut entities = String::new();
        entities.push_str("# AUTO-GENERATED by idl-emitters · do not edit\n");
        entities.push_str("# Target: python · Section: entities\n\n");
        entities
            .push_str("from dataclasses import dataclass\nfrom typing import Any, Optional\n\n");
        let mut entity_count = 0;
        for node in graph.nodes_of_kind("entity") {
            let name = pascal_case(&node_name(node));
            entities.push_str(&format!("# GENERATED_FROM {}\n", node.id));
            entities.push_str("@dataclass\n");
            entities.push_str(&format!("class {name}:\n"));
            let mut field_count = 0;
            if let Some(attrs) = node.props.get("attributes").and_then(|v| v.as_array()) {
                for attr in attrs {
                    let aname = attr.get("name").and_then(|v| v.as_str()).unwrap_or("field");
                    let atype = attr.get("type").and_then(|v| v.as_str()).unwrap_or("Any");
                    let nullable = attr
                        .get("nullable")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(false);
                    let py_ty = map_type_to_python(atype);
                    let ty = if nullable {
                        format!("Optional[{py_ty}]")
                    } else {
                        py_ty
                    };
                    entities.push_str(&format!("    {}: {}\n", safe_ident(&snake_case(aname)), ty));
                    field_count += 1;
                }
            }
            if field_count == 0 {
                entities.push_str("    pass\n");
            }
            entities.push('\n');
            entity_count += 1;
        }
        if entity_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("idl_generated/entities.py"),
                content: entities,
            });
            report.nodes_emitted += entity_count;
        }

        let mut operations = String::new();
        operations.push_str("# AUTO-GENERATED by idl-emitters · do not edit\n");
        operations.push_str("# Target: python · Section: operations\n\n");
        operations.push_str("from typing import Any, Protocol\n\n");
        operations.push_str("class Operations(Protocol):\n");
        let mut op_count = 0;
        for node in graph.nodes_of_kind("operation") {
            let name = safe_ident(&snake_case(&node_name(node)));
            operations.push_str(&format!("    # GENERATED_FROM {}\n", node.id));
            operations.push_str(&format!(
                "    def {name}(self{} ) -> {}: ...\n\n",
                inputs_signature(node),
                output_signature(node)
            ));
            op_count += 1;
        }
        if op_count == 0 {
            operations.push_str("    pass\n");
        }
        if op_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("idl_generated/operations.py"),
                content: operations,
            });
            report.nodes_emitted += op_count;
        }

        let mut api = String::new();
        api.push_str("# AUTO-GENERATED by idl-emitters · do not edit\n");
        api.push_str("# Target: python · Section: api route table\n\n");
        api.push_str("ROUTES = [\n");
        let mut api_count = 0;
        for node in graph.nodes_of_kind("api") {
            api.push_str(&format!("    # GENERATED_FROM {}\n", node.id));
            if let Some(eps) = node.props.get("endpoints").and_then(|v| v.as_array()) {
                for ep in eps {
                    let method = ep.get("method").and_then(|v| v.as_str()).unwrap_or("GET");
                    let path = ep.get("path").and_then(|v| v.as_str()).unwrap_or("/");
                    let opid = ep
                        .get("operation_id")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    api.push_str(&format!(
                        "    {{'method': {:?}, 'path': {:?}, 'operation_id': {:?}}},\n",
                        method, path, opid
                    ));
                }
            }
            api_count += 1;
        }
        api.push_str("]\n");
        if api_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("idl_generated/api.py"),
                content: api,
            });
            report.nodes_emitted += api_count;
        }

        let mut init = String::new();
        init.push_str("# AUTO-GENERATED by idl-emitters · do not edit\n");
        if entity_count > 0 {
            init.push_str("from .entities import *\n");
        }
        if op_count > 0 {
            init.push_str("from .operations import *\n");
        }
        report.files.push(EmittedFile {
            path: PathBuf::from("idl_generated/__init__.py"),
            content: init,
        });

        Ok(report)
    }
}

fn map_type_to_python(t: &str) -> String {
    match t.to_lowercase().as_str() {
        "string" | "text" | "uuid" | "datetime" | "timestamp" => "str".into(),
        "int" | "integer" | "long" | "bigint" => "int".into(),
        "float" | "double" | "number" => "float".into(),
        "bool" | "boolean" => "bool".into(),
        "json" => "Any".into(),
        other => pascal_case(other),
    }
}

fn inputs_signature(node: &idl_graph::NodeDoc) -> String {
    let mut s = String::new();
    if let Some(inputs) = node.props.get("inputs").and_then(|v| v.as_array()) {
        for inp in inputs {
            let n = inp.get("name").and_then(|v| v.as_str()).unwrap_or("arg");
            let t = inp.get("type").and_then(|v| v.as_str()).unwrap_or("Any");
            s.push_str(&format!(
                ", {}: {}",
                safe_ident(&snake_case(n)),
                map_type_to_python(t)
            ));
        }
    }
    s
}

fn output_signature(node: &idl_graph::NodeDoc) -> String {
    if let Some(outs) = node.props.get("outputs").and_then(|v| v.as_array()) {
        if outs.len() == 1 {
            let t = outs[0]
                .get("type")
                .and_then(|v| v.as_str())
                .unwrap_or("Any");
            return map_type_to_python(t);
        }
        if outs.len() > 1 {
            return "dict[str, Any]".into();
        }
    }
    "None".into()
}
