//! Rust target — entities → struct, operations → trait fn, api → axum
//! route stubs, state_machines → enum + transition fn.

use std::path::PathBuf;

use anyhow::Result;
use idl_graph::GraphDoc;

use super::{node_name, pascal_case, safe_ident, snake_case, EmitReport, EmittedFile, GraphEmitter};

pub struct RustEmitter;

impl GraphEmitter for RustEmitter {
    fn target(&self) -> &str {
        "rust"
    }

    fn emit(&self, graph: &GraphDoc) -> Result<EmitReport> {
        let mut report = EmitReport {
            target: "rust".into(),
            files: Vec::new(),
            nodes_emitted: 0,
        };

        // entities
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: rust · Section: entities\n\n");
        s.push_str("use serde::{Deserialize, Serialize};\n\n");
        let mut entity_count = 0;
        for node in graph.nodes_of_kind("entity") {
            let name = pascal_case(&node_name(node));
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            s.push_str("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
            s.push_str(&format!("pub struct {name} {{\n"));
            if let Some(attrs) = node.props.get("attributes").and_then(|v| v.as_array()) {
                for attr in attrs {
                    let aname = attr.get("name").and_then(|v| v.as_str()).unwrap_or("field");
                    let atype = attr.get("type").and_then(|v| v.as_str()).unwrap_or("String");
                    let nullable = attr.get("nullable").and_then(|v| v.as_bool()).unwrap_or(false);
                    let rust_ty = map_type_to_rust(atype);
                    let ty = if nullable { format!("Option<{rust_ty}>") } else { rust_ty };
                    s.push_str(&format!("    pub {}: {},\n", safe_ident(&snake_case(aname)), ty));
                }
            }
            s.push_str("}\n\n");
            entity_count += 1;
        }
        if entity_count > 0 {
            report.files.push(EmittedFile { path: PathBuf::from("src/entities.rs"), content: s });
            report.nodes_emitted += entity_count;
        }

        // operations
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: rust · Section: operations\n\n");
        s.push_str("use anyhow::Result;\n\n");
        let mut op_count = 0;
        s.push_str("pub trait Operations {\n");
        for node in graph.nodes_of_kind("operation") {
            let name = snake_case(&node_name(node));
            s.push_str(&format!("    // GENERATED_FROM {}\n", node.id));
            let inputs = inputs_signature(node);
            let outputs = outputs_signature_rust(node);
            s.push_str(&format!(
                "    fn {}(&self{}) -> Result<{}>;\n\n",
                safe_ident(&name), inputs, outputs
            ));
            op_count += 1;
        }
        s.push_str("}\n");
        if op_count > 0 {
            report.files.push(EmittedFile { path: PathBuf::from("src/operations.rs"), content: s });
            report.nodes_emitted += op_count;
        }

        // api → routes
        let mut api_emitted = 0;
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: rust · Section: api routes (axum)\n\n");
        s.push_str("use axum::Router;\nuse axum::routing::{get, post, put, delete, patch};\n\n");
        s.push_str("pub fn router() -> Router {\n    Router::new()\n");
        for node in graph.nodes_of_kind("api") {
            s.push_str(&format!("    // GENERATED_FROM {}\n", node.id));
            if let Some(eps) = node.props.get("endpoints").and_then(|v| v.as_array()) {
                for ep in eps {
                    let method = ep.get("method").and_then(|v| v.as_str()).unwrap_or("GET").to_lowercase();
                    let path = ep.get("path").and_then(|v| v.as_str()).unwrap_or("/");
                    let opid = ep.get("operation_id").and_then(|v| v.as_str()).unwrap_or("");
                    let handler = safe_ident(&snake_case(opid.rsplit_once(':').map(|(_, s)| s).unwrap_or(opid)));
                    let handler = if handler.is_empty() { "todo".to_string() } else { handler };
                    s.push_str(&format!("        .route({:?}, {}({}_handler))\n", path, method, handler));
                }
            }
            api_emitted += 1;
        }
        s.push_str("}\n");
        if api_emitted > 0 {
            report.files.push(EmittedFile { path: PathBuf::from("src/routes.rs"), content: s });
            report.nodes_emitted += api_emitted;
        }

        // state machines
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: rust · Section: state machines\n\n");
        let mut sm_count = 0;
        for node in graph.nodes_of_kind("state_machine") {
            let raw_name = node.props.get("entity_or_aggregate").and_then(|v| v.as_str())
                .map(|s| s.to_string()).unwrap_or_else(|| node_name(node));
            let name = pascal_case(&raw_name);
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
            s.push_str(&format!("pub enum {name}State {{\n"));
            if let Some(states) = node.props.get("states").and_then(|v| v.as_array()) {
                for st in states {
                    if let Some(ss) = st.as_str() {
                        s.push_str(&format!("    {},\n", pascal_case(ss)));
                    }
                }
            }
            s.push_str("}\n\n");
            s.push_str(&format!(
                "pub fn {0}_transition(state: {1}State, trigger: &str) -> Option<{1}State> {{\n",
                snake_case(&raw_name), name
            ));
            s.push_str("    match (state, trigger) {\n");
            if let Some(trs) = node.props.get("transitions").and_then(|v| v.as_array()) {
                for t in trs {
                    let from = t.get("from").and_then(|v| v.as_str()).unwrap_or("?");
                    let to = t.get("to").and_then(|v| v.as_str()).unwrap_or("?");
                    let trigger = t.get("trigger").and_then(|v| v.as_str()).unwrap_or("?");
                    s.push_str(&format!(
                        "        ({0}State::{1}, {2:?}) => Some({0}State::{3}),\n",
                        name, pascal_case(from), trigger, pascal_case(to)
                    ));
                }
            }
            s.push_str("        _ => None,\n    }\n}\n\n");
            sm_count += 1;
        }
        if sm_count > 0 {
            report.files.push(EmittedFile { path: PathBuf::from("src/state_machines.rs"), content: s });
            report.nodes_emitted += sm_count;
        }

        // root
        let mut root = String::new();
        root.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        root.push_str("// Crate root for IDL-generated scaffolding.\n\n");
        if entity_count > 0 { root.push_str("pub mod entities;\n"); }
        if op_count > 0 { root.push_str("pub mod operations;\n"); }
        if api_emitted > 0 { root.push_str("pub mod routes;\n"); }
        if sm_count > 0 { root.push_str("pub mod state_machines;\n"); }
        report.files.push(EmittedFile { path: PathBuf::from("src/lib.rs"), content: root });

        Ok(report)
    }
}

fn map_type_to_rust(t: &str) -> String {
    match t.to_lowercase().as_str() {
        "string" | "text" | "uuid" => "String".into(),
        "int" | "integer" | "i32" => "i32".into(),
        "long" | "i64" | "bigint" => "i64".into(),
        "float" | "f32" => "f32".into(),
        "double" | "f64" | "number" => "f64".into(),
        "bool" | "boolean" => "bool".into(),
        "datetime" | "timestamp" => "String".into(),
        "json" => "serde_json::Value".into(),
        other => pascal_case(other),
    }
}

fn inputs_signature(node: &idl_graph::NodeDoc) -> String {
    let mut s = String::new();
    if let Some(inputs) = node.props.get("inputs").and_then(|v| v.as_array()) {
        for inp in inputs {
            let n = inp.get("name").and_then(|v| v.as_str()).unwrap_or("arg");
            let t = inp.get("type").and_then(|v| v.as_str()).unwrap_or("String");
            let nullable = inp.get("nullable").and_then(|v| v.as_bool()).unwrap_or(false);
            let rty = map_type_to_rust(t);
            let ty = if nullable { format!("Option<{rty}>") } else { rty };
            s.push_str(&format!(", {}: {}", safe_ident(&snake_case(n)), ty));
        }
    }
    s
}

fn outputs_signature_rust(node: &idl_graph::NodeDoc) -> String {
    if let Some(outs) = node.props.get("outputs").and_then(|v| v.as_array()) {
        if outs.len() == 1 {
            let t = outs[0].get("type").and_then(|v| v.as_str()).unwrap_or("()");
            return map_type_to_rust(t);
        } else if outs.len() > 1 {
            let parts: Vec<String> = outs.iter()
                .map(|o| map_type_to_rust(o.get("type").and_then(|v| v.as_str()).unwrap_or("()")))
                .collect();
            return format!("({})", parts.join(", "));
        }
    }
    "()".into()
}
