//! TypeScript target — entities → interface, operations → fn signatures,
//! api → fetch client + route types, state_machines → string union + reducer.

use std::path::PathBuf;

use anyhow::Result;
use idl_graph::GraphDoc;

use super::{node_name, pascal_case, snake_case, EmitReport, EmittedFile, GraphEmitter};

pub struct TypeScriptEmitter;

impl GraphEmitter for TypeScriptEmitter {
    fn target(&self) -> &str {
        "typescript"
    }

    fn emit(&self, graph: &GraphDoc) -> Result<EmitReport> {
        let mut report = EmitReport {
            target: "typescript".into(),
            ..Default::default()
        };

        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: typescript · Section: entities\n\n");
        let mut entity_count = 0;
        for node in graph.nodes_of_kind("entity") {
            let name = pascal_case(&node_name(node));
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            s.push_str(&format!("export interface {name} {{\n"));
            if let Some(attrs) = node.props.get("attributes").and_then(|v| v.as_array()) {
                for attr in attrs {
                    let aname = attr.get("name").and_then(|v| v.as_str()).unwrap_or("field");
                    let atype = attr
                        .get("type")
                        .and_then(|v| v.as_str())
                        .unwrap_or("string");
                    let nullable = attr
                        .get("nullable")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(false);
                    let q = if nullable { "?" } else { "" };
                    s.push_str(&format!("  {}{}: {};\n", aname, q, map_type_to_ts(atype)));
                }
            }
            s.push_str("}\n\n");
            entity_count += 1;
        }
        if entity_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("src/entities.ts"),
                content: s,
            });
            report.nodes_emitted += entity_count;
        }

        // operations
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: typescript · Section: operations\n\n");
        let mut op_count = 0;
        for node in graph.nodes_of_kind("operation") {
            let name = snake_case(&node_name(node)).replace('_', "-");
            let cname = pascal_case(&name);
            let inputs = inputs_to_ts(node);
            let output = output_to_ts(node);
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            s.push_str(&format!("export type {cname}Input = {{\n{}}};\n", inputs));
            s.push_str(&format!("export type {cname}Output = {output};\n"));
            s.push_str(&format!(
                "export type {cname}Fn = (input: {cname}Input) => Promise<{cname}Output>;\n\n"
            ));
            op_count += 1;
        }
        if op_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("src/operations.ts"),
                content: s,
            });
            report.nodes_emitted += op_count;
        }

        // api → fetch client
        let mut api_emitted = 0;
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: typescript · Section: api fetch client\n\n");
        s.push_str(
            "export interface Endpoint { method: string; path: string; operationId: string; }\n\n",
        );
        for node in graph.nodes_of_kind("api") {
            let aname = pascal_case(&node_name(node));
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            s.push_str(&format!("export const {aname}Routes: Endpoint[] = [\n"));
            if let Some(eps) = node.props.get("endpoints").and_then(|v| v.as_array()) {
                for ep in eps {
                    let method = ep.get("method").and_then(|v| v.as_str()).unwrap_or("GET");
                    let path = ep.get("path").and_then(|v| v.as_str()).unwrap_or("/");
                    let opid = ep
                        .get("operation_id")
                        .and_then(|v| v.as_str())
                        .unwrap_or("");
                    s.push_str(&format!(
                        "  {{ method: {:?}, path: {:?}, operationId: {:?} }},\n",
                        method, path, opid
                    ));
                }
            }
            s.push_str("];\n\n");
            s.push_str(&format!(
                "export function create{aname}Client(baseUrl: string) {{\n  return {{\n    async call(operationId: string, init?: RequestInit) {{\n      const ep = {aname}Routes.find(r => r.operationId === operationId);\n      if (!ep) throw new Error(`unknown operation: ${{operationId}}`);\n      return fetch(baseUrl + ep.path, {{ method: ep.method, ...init }});\n    }}\n  }};\n}}\n\n"
            ));
            api_emitted += 1;
        }
        if api_emitted > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("src/api.ts"),
                content: s,
            });
            report.nodes_emitted += api_emitted;
        }

        // state machines
        let mut s = String::new();
        s.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        s.push_str("// Target: typescript · Section: state machines\n\n");
        let mut sm_count = 0;
        for node in graph.nodes_of_kind("state_machine") {
            let raw = node
                .props
                .get("entity_or_aggregate")
                .and_then(|v| v.as_str())
                .map(|s| s.to_string())
                .unwrap_or_else(|| node_name(node));
            let name = pascal_case(&raw);
            s.push_str(&format!("// GENERATED_FROM {}\n", node.id));
            let states: Vec<String> = node
                .props
                .get("states")
                .and_then(|v| v.as_array())
                .map(|a| {
                    a.iter()
                        .filter_map(|v| v.as_str().map(String::from))
                        .collect()
                })
                .unwrap_or_default();
            let union = if states.is_empty() {
                "string".to_string()
            } else {
                states
                    .iter()
                    .map(|s| format!("{:?}", s))
                    .collect::<Vec<_>>()
                    .join(" | ")
            };
            s.push_str(&format!("export type {name}State = {union};\n\n"));
            s.push_str(&format!(
                "export function reduce{name}(state: {name}State, trigger: string): {name}State {{\n  switch (state + '/' + trigger) {{\n"
            ));
            if let Some(trs) = node.props.get("transitions").and_then(|v| v.as_array()) {
                for t in trs {
                    let from = t.get("from").and_then(|v| v.as_str()).unwrap_or("?");
                    let to = t.get("to").and_then(|v| v.as_str()).unwrap_or("?");
                    let trigger = t.get("trigger").and_then(|v| v.as_str()).unwrap_or("?");
                    s.push_str(&format!(
                        "    case {:?}: return {:?};\n",
                        format!("{}/{}", from, trigger),
                        to
                    ));
                }
            }
            s.push_str("    default: return state;\n  }\n}\n\n");
            sm_count += 1;
        }
        if sm_count > 0 {
            report.files.push(EmittedFile {
                path: PathBuf::from("src/stateMachines.ts"),
                content: s,
            });
            report.nodes_emitted += sm_count;
        }

        let mut idx = String::new();
        idx.push_str("// AUTO-GENERATED by idl-emitters · do not edit\n");
        if entity_count > 0 {
            idx.push_str("export * from \"./entities\";\n");
        }
        if op_count > 0 {
            idx.push_str("export * from \"./operations\";\n");
        }
        if api_emitted > 0 {
            idx.push_str("export * from \"./api\";\n");
        }
        if sm_count > 0 {
            idx.push_str("export * from \"./stateMachines\";\n");
        }
        report.files.push(EmittedFile {
            path: PathBuf::from("src/index.ts"),
            content: idx,
        });

        Ok(report)
    }
}

fn map_type_to_ts(t: &str) -> String {
    match t.to_lowercase().as_str() {
        "string" | "text" | "uuid" | "datetime" | "timestamp" => "string".into(),
        "int" | "integer" | "long" | "bigint" | "float" | "double" | "number" => "number".into(),
        "bool" | "boolean" => "boolean".into(),
        "json" => "unknown".into(),
        other => pascal_case(other),
    }
}

fn inputs_to_ts(node: &idl_graph::NodeDoc) -> String {
    let mut s = String::new();
    if let Some(inputs) = node.props.get("inputs").and_then(|v| v.as_array()) {
        for inp in inputs {
            let n = inp.get("name").and_then(|v| v.as_str()).unwrap_or("arg");
            let t = inp.get("type").and_then(|v| v.as_str()).unwrap_or("string");
            let nullable = inp
                .get("nullable")
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            let q = if nullable { "?" } else { "" };
            s.push_str(&format!("  {}{}: {};\n", n, q, map_type_to_ts(t)));
        }
    }
    s
}

fn output_to_ts(node: &idl_graph::NodeDoc) -> String {
    if let Some(outs) = node.props.get("outputs").and_then(|v| v.as_array()) {
        if outs.len() == 1 {
            let t = outs[0]
                .get("type")
                .and_then(|v| v.as_str())
                .unwrap_or("void");
            return map_type_to_ts(t);
        } else if outs.len() > 1 {
            let parts: Vec<String> = outs
                .iter()
                .map(|o| {
                    let n = o.get("name").and_then(|v| v.as_str()).unwrap_or("v");
                    let t = o.get("type").and_then(|v| v.as_str()).unwrap_or("unknown");
                    format!("{}: {}", n, map_type_to_ts(t))
                })
                .collect();
            return format!("{{ {} }}", parts.join("; "));
        }
    }
    "void".into()
}
