//! `idl init` (P6.6) — scaffolds the standard `intent/` layout.

use std::path::{Path, PathBuf};
use std::process::ExitCode;

use anyhow::{bail, Context, Result};
use serde_json::json;

const PROJECT_IDL_GREENFIELD: &str = "version: \"0.5.0\"\n\
\n\
# Intent project. Generated by `idl init --greenfield`.\n\
# Add kernel blocks (intent, scope, entity, …) below.\n\
\n\
intent ProjectIntent {\n\
  goal: \"State the primary outcome this project must deliver.\"\n\
  actors: []\n\
}\n";

pub fn run(
    dir: PathBuf,
    greenfield: bool,
    brownfield: bool,
    source: Option<PathBuf>,
    ctx: &crate::output::OutputContext,
) -> Result<ExitCode> {
    if greenfield == brownfield {
        bail!("pass exactly one of --greenfield or --brownfield");
    }

    let intent = dir.join("intent");
    std::fs::create_dir_all(&intent).with_context(|| format!("create {}", intent.display()))?;

    write_config(&intent, brownfield)?;

    if greenfield {
        scaffold_greenfield(&intent)?;
        ctx.stdout(&format!(
            "✓ greenfield init at {}\n  intent/project.idl\n  intent/changes/0001-initial-intent/\n  intent/.idl/config.json",
            dir.display()
        ));
    } else {
        let src = source.expect("clap requires --source with --brownfield");
        scaffold_brownfield(&intent, &src)?;
        ctx.stdout(&format!(
            "✓ brownfield init at {}\n  intent/extracted/ (placeholder)\n  intent/changes/0001-promote-extraction/\n  intent/.idl/config.json\n  source: {}\n  next: run `idl extract --source {} --output intent/extracted` once adapters land.",
            dir.display(),
            src.display(),
            src.display()
        ));
    }

    Ok(crate::exit_codes::success())
}

fn write_config(intent: &Path, brownfield: bool) -> Result<()> {
    let dot = intent.join(".idl");
    std::fs::create_dir_all(&dot)?;
    let cfg = json!({
        "schema_version": "0.1.0",
        "mode": if brownfield { "brownfield" } else { "greenfield" },
        "kernel_version": "v0.1.0",
        "created_by": "idl init"
    });
    std::fs::write(
        dot.join("config.json"),
        serde_json::to_string_pretty(&cfg)? + "\n",
    )?;
    Ok(())
}

fn scaffold_greenfield(intent: &Path) -> Result<()> {
    let project_idl = intent.join("project.idl");
    if !project_idl.exists() {
        std::fs::write(&project_idl, PROJECT_IDL_GREENFIELD)?;
    }
    scaffold_change(intent, "0001-initial-intent", "draft", BOOTSTRAP_DECISION)?;
    Ok(())
}

fn scaffold_brownfield(intent: &Path, source: &Path) -> Result<()> {
    let extracted = intent.join("extracted");
    std::fs::create_dir_all(&extracted)?;
    let manifest = json!({
        "source": source.display().to_string(),
        "status": "pending",
        "note": "Run `idl extract` once language adapters land."
    });
    std::fs::write(
        extracted.join("source-manifest.json"),
        serde_json::to_string_pretty(&manifest)? + "\n",
    )?;
    scaffold_change(
        intent,
        "0001-promote-extraction",
        "draft",
        BOOTSTRAP_DECISION_BROWNFIELD,
    )?;
    Ok(())
}

const BOOTSTRAP_DECISION: &str = "# Decision: initial intent\n\n\
- **Status:** draft\n\
- **Context:** First change for a freshly initialized IDL project.\n\
- **Decision:** TBD — describe the first intent to accept.\n\
- **Consequences:** Sets the baseline `project.idl` for the project.\n";

const BOOTSTRAP_DECISION_BROWNFIELD: &str = "# Decision: promote extraction\n\n\
- **Status:** draft\n\
- **Context:** Brownfield init — `intent/extracted/` will be populated by `idl extract`.\n\
- **Decision:** Pending extraction run; promote inferred intent to accepted blocks.\n\
- **Consequences:** Establishes the canonical `project.idl` from existing code.\n";

pub fn scaffold_change(
    intent: &Path,
    slug: &str,
    state: &str,
    decision_template: &str,
) -> Result<()> {
    let folder = intent.join("changes").join(slug);
    std::fs::create_dir_all(&folder)?;

    let now = iso_now();
    let state_json = json!({
        "id": slug,
        "state": state,
        "created_at": now,
        "updated_at": now,
        "transitions": []
    });
    std::fs::write(
        folder.join("state.json"),
        serde_json::to_string_pretty(&state_json)? + "\n",
    )?;
    std::fs::write(
        folder.join("intent-delta.idl"),
        "# proposed intent delta — keep small and focused\n",
    )?;
    std::fs::write(folder.join("decisions.md"), decision_template)?;
    Ok(())
}

/// RFC3339-ish UTC timestamp without bringing in chrono.
fn iso_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format_unix_seconds(secs)
}

fn format_unix_seconds(secs: u64) -> String {
    // Days from epoch.
    let days = (secs / 86_400) as i64;
    let secs_today = (secs % 86_400) as u32;
    let (y, m, d) = days_to_ymd(days);
    let hh = secs_today / 3600;
    let mm = (secs_today % 3600) / 60;
    let ss = secs_today % 60;
    format!("{y:04}-{m:02}-{d:02}T{hh:02}:{mm:02}:{ss:02}Z")
}

fn days_to_ymd(mut days: i64) -> (i32, u32, u32) {
    // Civil-from-days (Howard Hinnant's algorithm).
    days += 719_468;
    let era = if days >= 0 { days } else { days - 146_096 } / 146_097;
    let doe = (days - era * 146_097) as u32;
    let yoe = (doe
        .wrapping_sub(doe / 1460)
        .wrapping_sub(doe / 36_524)
        .wrapping_add(doe / 146_096))
        / 365;
    let y = yoe as i32 + era as i32 * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y, m, d)
}
